[package]
name = "ticket_to_ics"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf2image = "0.1.3"
base64 = "0.22.1"
futures = "0.3.31"
openrouter_api = "0.3.2"
tokio = "1.48.0"
anyhow = "1.0.100"
notify = "8.2.0"
